services:
  php:
    build:
      context: ./php
    container_name: php_symfony
    ports:
      - 8080:80
    volumes:
      - ./app:/var/www/html
      - ./apache/default.conf:/etc/apache2/sites-enabled/000-default.conf

  database:
    image: mysql:8.0
    container_name: mysql_symfony
    environment:
      MYSQL_ROOT_PASSWORD: cequejeveux
      MYSQL_DATABASE: base_symfony
      MYSQL_USER: symfony
      MYSQL_PASSWORD: azerty
    volumes:
      - ./mysql:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin
    environment:
      PMA_HOST: database
      PMA_USER: root
      PMA_PASSWORD: cequejeveux
    ports:
      - 8081:80
    depends_on:
      - database

  mailhog:
    image: mailhog/mailhog
    ports:
      - 8025:8025
